# These are supported funding model platforms

github: Abhijitam01
# patreon: # Replace with up to 4 Patreon usernames
# open_collective: # Replace with one Open Collective username
# ko_fi: # Replace with one Ko-fi username
# tidelift: # Replace with one Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with up to 4 Community Bridge project names e.g., cloud-foundry
# liberapay: # Replace with one Liberapay username
# issuehunt: # Replace with one IssueHunt username
# otechie: # Replace with one Otechie username
# lfx_crowdfunding: # Replace with up to 4 LFX Crowdfunding project names e.g., cloud-foundry
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

